### ISSUE TITLE
Suggestion: Add more features of mods into this one

### ISSUE THREAD

**Issue by Epyx15** [TpdeaX/BetterPause-Geode#26]
Basically there are small mods that already add small things to the pause menu and my suggestion is to add them as part of this one. Example: coins in pause menu and level info in pause menu. You could add the features of those mods in this one so you can adapt them to this mod, since we already have some like settings on pause menu, hide pause menu, comment section on pause menu, etc.

**Comment by TpdeaX** [comment]
in fact most of them are being adapted for betterPause, I will try to put them but to make it active, but it will always be recommended to mods that are already done.

**Comment by Epyx15** [comment]
Oh, I see. That's cool!
