### ISSUE TITLE
Suggestion: Remove exit hotkey

### ISSUE THREAD

**Issue by TeahersAreStupid1234** [TpdeaX/BetterPause-Geode#36]
When you are in pause menu you can press esc again to quit the entire level, which can be very annoying when pressed on accident. I recommend a feature to remove that.

**Comment by TpdeaX** [comment]
I can implement the hack to remove the exit button key, but I don't think it will be useful considering that several mods already have that. You can use the confirm exit option for a better experience, but I'll still try to implement it.

**Comment by TeahersAreStupid1234** [comment]
its added :)
