### ISSUE TITLE
[BUG] Metaphysical bug with QOL.

### ISSUE THREAD

**Issue by Pony-CW** [TpdeaX/BetterPause-Geode#43]
### **Reproduce**

>English is not good, the following is Deepl machine translation

1. Open the pause page normally
2. Open QOL page
3. Do not close the QOL page and penetrate the QOL page and click the continue button.
4. Gesture back to trigger the pause to penetrate the QOL page and click on the exit.
5. Enter any level, can not click the pause button normally, only gesture back to pause

https://github.com/TpdeaX/BetterPause-Geode/assets/44076275/9f5d4fcd-799d-4f1b-9b8c-2cdbc1bec84b

### **Logs**

> Last 5 for reference

![logs.zip](https://github.com/TpdeaX/BetterPause-Geode/files/14871832/logs.zip)

### **Game Version**
Android 2.205
### **Geode Version**
v2.0.0.beta.23 nightly-9f2cea4

**Comment by TpdeaX** [comment]
I'll try to fix it, but I think it's a QOL issue.
