### ISSUE TITLE
Some mods don't load after updating to 2.206

### ISSUE THREAD

**Issue by Cxzcan** [TpdeaX/BetterPause-Geode#57]
![Screenshot_20240602-181239_Geode](https://github.com/TpdeaX/BetterPause-Geode/assets/171485730/12aee761-893b-4e1f-b1a6-085715a7deaa)

**Comment by slideglide** [comment]
not an issue related to betterpause, it's because you have the version of geode and mods that dont support 2.206

**Comment by Cxzcan** [comment]
> not an issue related to betterpause, it's because you have the version of geode and mods that dont support 2.206
Sorry i dont know im commenting in betterpause section

**Comment by Cxzcan** [comment]
> not an issue related to betterpause, it's because you have the version of geode and mods that dont support 2.206

Sorry i dont know im commenting in betterpause section
